version: "3"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    entrypoint:
      - node
      - src/index
      - --config=./.config.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - database
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        PUBLIC_PATH: "${FRONTEND_PUBLIC_PATH}"
        AUTH_PATH: "${FRONTEND_AUTH_PATH}"
    env_file:
      - .env
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    links:
      - backend
    depends_on:
      - backend

  database:
    image: "mongo"
    volumes:
      - database_mongo:/data/db
    restart: unless-stopped

volumes:
  database_mongo: