version: "3"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    entrypoint:
      - node
      - src/index
      - --api
      - --config=./.config.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - object_cache:/app/data/cache
    links:
      - database
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        PUBLIC_PATH: "${FRONTEND_PUBLIC_PATH}"
        AUTH_PATH: "${FRONTEND_AUTH_PATH}"
    env_file:
      - .env
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    links:
      - backend
    depends_on:
      - backend

  database:
    image: couchdb:latest
    environment:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: 123qwe
    volumes:
      - database:/opt/couchdb/data

volumes:
    database:
    object_cache:
