version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    entrypoint:
      - node
      - src/index
      - --config=./.config.prod.js
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock