version: "3"

services:
  backend:
    build: ./backend/
    entrypoint:
      - node
      - src/index
      - --api
      - --config=./.config.docker.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - database
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        PUBLIC_PATH: /
    ports:
      - "8080:80"
    links:
      - backend
    depends_on:
      - backend
  database:
    image: couchdb:latest
    volumes:
      - database:/opt/couchdb/data