version: "3"

services:
  backend:
    build: ./
    entrypoint:
      - node
      - src/index
      - --config=./.config.prod.js
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend/
    ports:
      - "8080:80"
    links:
      - backend
    depends_on:
      - backend