version: "3"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        AUTH_API: "${BACKEND_AUTH_API}"
    env_file:
      - .env
    entrypoint:
      - node
      - src/index
      - --api
      - --config=./.config.docker.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - database
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        PUBLIC_PATH: "${FRONTEND_PUBLIC_PATH}"
        AUTH_PATH: "${FRONTEND_AUTH_PATH}"
    env_file:
      - .env
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    links:
      - backend
    depends_on:
      - backend
  database:
    image: couchdb:latest
    environment:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: 123qwe
    volumes:
      - database:/opt/couchdb/data

volumes:
    database:
