[sources.frontend_nginx]
  type = "syslog"
  mode = "udp"
  address = "0.0.0.0:514"

[sinks.loki]
  type = "loki"
  inputs = ["frontend_nginx"]
  endpoint = "http://loki:3100"
  encoding.codec = "json"
  labels.app = "frontend/ngixn"